services:
  backend:
    container_name: spezi-study-platform_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    env_file: .env
    ports:
      - "${WEB_PORT:-80}:80"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - postgres

  postgres:
    container_name: spezi-study-platform_db
    image: postgres:16
    env_file: .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./.db_data:/var/lib/postgresql/data

  
